name: UI API Hybrid Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run Playwright + Pytest Tests
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # 3️⃣ Upgrade pip & install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright browsers
        run: |
          playwright install --with-deps

      # 5️⃣ Run tests
      - name: Run tests
        env:
          ENV: qa
          BASE_URL: https://practice.expandtesting.com
          LOGIN_URL: https://practice.expandtesting.com/login
          USERNAME: practice
          PASSWORD: practice
          HEADLESS: true
        run: |
          pytest
